# This file was generated by GoReleaser. DO NOT EDIT.
cask "oxygen" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "339a945dd0fb42237334b716e3d7d8239a65a984284a8b7fce9c493d6f7363c7"
      url "https://github.com/beeemT/oxygen/releases/download/v#{version}/oxygen_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c085252e9781a15d6ba44f527b68bf1b9f4af18b9091e961c65db571e21aa69"
      url "https://github.com/beeemT/oxygen/releases/download/v#{version}/oxygen_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0aecc91648a2106d009a7d164f206e8edf78d3ea901f265b7bb25ce25c9e72b8"
      url "https://github.com/beeemT/oxygen/releases/download/v#{version}/oxygen_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bff55c27877c6ecd77fb1b318af0fe14645e7c2f53b12c531484c3790e62c802"
      url "https://github.com/beeemT/oxygen/releases/download/v#{version}/oxygen_#{version}_linux_arm64.tar.gz"
    end
  end

  name "oxygen"
  desc "CLI for OpenObserve — query logs, metrics, traces and manage the platform"
  homepage "https://github.com/beeemT/oxygen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oxygen"
  fish_completion "completions/o2.fish"
  zsh_completion "completions/_o2"

  # No zap stanza required

end
